<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
ویژگی‌های دسته‌ای
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
خواندن مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
ابتدا نیاز است فایل مجموعه‌داده‌ی بدون مقادیر گم‌شده (<code>beijing_no_missing.csv</code>) را بخوانیم.
</p>

In [1]:
import pandas as pd
# reading the dataset
df = pd.read_csv('../beijing_no_missing.csv', encoding='gbk', low_memory=False, parse_dates=['tradeTime'])

In [2]:
df

,url,id,Lng,Lat,Cid,tradeTime,DOM,followers,totalPrice,price,...,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,price_category,buildingStrucure_ismissing,buildingType_ismissing
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030,116.475489,40.019520,1111027376244,2016-08-09,1464.0,106,415.0,31680,...,steel-concrete composite,0.217,has elevator,no,has subway,7,56021.0,average,False,False
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217,116.453917,39.881534,1111027381879,2016-07-28,903.0,126,575.0,43436,...,steel-concrete composite,0.667,has elevator,yes,no subway,7,71539.0,average,False,False
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636,116.561978,39.877145,1111040862969,2016-12-11,1271.0,48,1030.0,52021,...,steel-concrete composite,0.500,has elevator,no,no subway,7,48160.0,average,False,False
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841,116.438010,40.076114,1111043185817,2016-09-30,965.0,138,297.5,22202,...,steel-concrete composite,0.273,has elevator,no,no subway,6,51238.0,cheap,False,False
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653,116.428392,39.886229,1111027381174,2016-08-28,927.0,286,392.0,48396,...,mixed,0.333,no elevator,yes,has subway,1,62588.0,average,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318814,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016-06-10,1.0,8,350.0,20580,...,steel-concrete composite,0.333,no elevator,yes,no subway,3,36545.0,cheap,False,False
318815,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016-06-10,1.0,1,108.8,31006,...,steel-concrete composite,0.222,has elevator,no,has subway,3,54282.0,average,False,False
318816,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016-06-05,1.0,2,359.0,35138,...,steel-concrete composite,0.500,has elevator,yes,no subway,3,46927.0,average,False,False
318817,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016-06-12,10.0,4,720.0,40373,...,mixed,0.500,no elevator,yes,no subway,3,54842.0,average,False,False
318818,https://bj.lianjia.com/chengjiao/BJYZ92363553....,BJYZ92363553,116.497474,39.810115,1111027377957,2016-06-11,1.0,0,450.0,48675,...,steel-concrete composite,1.000,has elevator,no,has subway,3,54282.0,average,False,False

<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
استخراج عدد روز، ماه و سال
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
در سلول زیر، روز، ماه و سال انجام معامله را به ترتیب با اسم‌های <code>tradeDay</code> و <code>tradeMonth</code> و <code>tradeYear</code> به مجموعه‌داده اضافه می‌کنیم:
</font>
</p>

In [3]:
df['tradeDay'] = df['tradeTime'].dt.day
df['tradeMonth'] = df['tradeTime'].dt.month
df['tradeYear'] = df['tradeTime'].dt.year

df[['tradeTime', 'tradeDay', 'tradeMonth', 'tradeYear']].head()

   tradeTime  tradeDay  tradeMonth  tradeYear
0 2016-08-09         9           8       2016
1 2016-07-28        28           7       2016
2 2016-12-11        11          12       2016
3 2016-09-30        30           9       2016
4 2016-08-28        28           8       2016

<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
استخراج نام روز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
در سلول زیر اسم روز (شنبه، یک‌شنبه و …) را به عنوان یک ویژگی دیگر با اسم <code>tradeDayName</code> به مجموعه‌داده اضافه می‌کنیم:

</font>
</p>

In [4]:
df['tradeDayName'] = df['tradeTime'].dt.day_name()

df[['tradeTime', 'tradeDayName']].head()

   tradeTime tradeDayName
0 2016-08-09      Tuesday
1 2016-07-28     Thursday
2 2016-12-11       Sunday
3 2016-09-30       Friday
4 2016-08-28       Sunday

<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
استخراج آخر سال بودن یا نبودن
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
به کمک سلول زیر، می‌توانیم آخر سال بودن یا نبودن یک تاریخ را به عنوان یک ویژگی جدید، با اسم <code>isTradeEndYear</code> اضافه کنیم:

</font>
</p>

In [5]:
df['isTradeEndYear'] = df['tradeTime'].dt.is_year_end

df[['tradeTime', 'isTradeEndYear']].head()

   tradeTime  isTradeEndYear
0 2016-08-09           False
1 2016-07-28           False
2 2016-12-11           False
3 2016-09-30           False
4 2016-08-28           False


<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
کشف فصل (گرم یا سرد)
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
در سلول زیر کدی می‌نویسیم که مشخص می‌کند <code>tradeTime</code> در فصل‌های گرم سال اتفاق افتاده است یا خیر. این ویژگی را با اسم <code>isHotMonth</code> اضافه می‌کنیم:

</font>
</p>

In [6]:
hot_weather = ['March', 'April', 'May', 'June', 'July', 'August']
cold_weather = ['September', 'October', 'November', 'December', 'January', 'February']

df['isHotMonth'] = [month in hot_weather for month in df['tradeTime'].dt.month_name()]

df[['tradeTime', 'isHotMonth']].head()

   tradeTime  isHotMonth
0 2016-08-09        True
1 2016-07-28        True
2 2016-12-11       False
3 2016-09-30       False
4 2016-08-28        True


<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
تقسیم‌بندی براساس سال ساخت
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
می‌خواهیم ساختمان‌ها را بر اساس سال ساخت‌شان به سه دسته تقسیم کنیم. دسته اول را به ساختمان‌هایی اختصاص می‌دهیم که بین سال‌های ۱۹۰۶ تا ۱۹۸۰ ساخته شده باشند. دسته دوم مخصوص ساختمان‌هایی است که سال ساختشان بین ۱۹۸۱ تا ۲۰۱۰ باشد و در دسته سوم، ساختمان‌هایی قرار می‌گیرند که [تقریباً] نوساز به حساب می‌آیند. سال ساخت این ساختمان‌ها باید حداقل ۲۰۱۱ باشد. این سه دسته را به ترتیب به سه عدد ۱، ۲ و ۳ نسبت می‌دهیم. در سلول زیر، ابتدا جنس ستون <code>constructionTime</code> را به <code>int</code> تغییر می‌دهیم:
</font>
</p>

In [7]:
df['constructionTime'] = df['constructionTime'].astype('int')

def categorize_year(year):
    if year <= 1980:
        return 1
    if year <= 2010:
        return 2
    return 3

df['buildingLife'] = df['constructionTime'].apply(categorize_year)

df[['constructionTime', 'buildingLife']].head()

   constructionTime  buildingLife
0              2005             2
1              2004             2
2              2005             2
3              2008             2
4              1960             1


<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
استخراج تعطیلی روز معامله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
ویژگی دیگری که می‌توان استخراج کرد، تعطیل بودن یا نبودن روزی است که در آن معامله انجام شده است. به این منظور می‌توانیم از کتابخانه‌ی <code>holidays</code> استفاده کنیم.
</font>
</p>

In [9]:
%pip install holidays
import holidays
china_holidays = holidays.China()
df['isDayOff'] = df['tradeTime'].apply(lambda date : date in china_holidays)

df[['tradeTime', 'isDayOff']].head()

Defaulting to user installation because normal site-packages is not writeable
Collecting holidays
  Downloading holidays-0.65-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: python-dateutil in c:\users\josef\appdata\roaming\python\python313\site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\josef\appdata\roaming\python\python313\site-packages (from python-dateutil->holidays) (1.17.0)
Downloading holidays-0.65-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.2 MB ? eta -:--:--
   ----------------- ---------------------- 0.5/1.2 MB 1.2 MB/s eta 0:00:01
   ------------------------- -------------- 0.8/1.2 MB 1.4 MB/s eta 0:00:01
   ---------------------------------- ----- 1.0/1.2 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 1.3 MB/s eta 0:00:00
Installing collected packages: holidays
Successfully installed holidays-0.65
Note: you may need to restart the kernel to use updated packages.

   tradeTime  isDayOff
0 2016-08-09     False
1 2016-07-28     False
2 2016-12-11     False
3 2016-09-30     False
4 2016-08-28     False

In [43]:
import holidays
iran_holidays = holidays.IR
iran_holidays(years=2025)

{datetime.date(2025, 3, 21): '(تخمین زده) کشته\u200cشدن علی بن ابی\u200cطالب; نوروز', datetime.date(2025, 3, 22): 'نوروز', datetime.date(2025, 3, 23): 'نوروز', datetime.date(2025, 3, 24): 'نوروز', datetime.date(2025, 4, 1): 'روز جمهوری اسلامی', datetime.date(2025, 4, 2): 'روز طبیعت', datetime.date(2025, 6, 4): 'درگذشت سید روح\u200cالله خمینی', datetime.date(2025, 6, 5): 'تظاهرات ۱۵ خرداد', datetime.date(2025, 2, 10): 'پیروزی انقلاب ۵۷', datetime.date(2025, 3, 19): 'ملی\u200cشدن صنعت نفت', datetime.date(2025, 7, 4): '(تخمین زده) تاسوعا', datetime.date(2025, 7, 5): '(تخمین زده) کشته\u200cشدن حسین بن علی، عاشورا', datetime.date(2025, 8, 14): '(تخمین زده) چهلم حسین بن علی اربعین', datetime.date(2025, 8, 22): '(تخمین زده) کشته\u200cشدن حسن مجتبی و درگذشت محمد', datetime.date(2025, 8, 23): '(تخمین زده) کشته\u200cشدن علی بن موسی الرضا', datetime.date(2025, 8, 31): '(تخمین زده) کشته\u200cشدن حسن عسکری', datetime.date(2025, 9, 9): '(تخمین زده) زادروز محمد و جعفر صادق', datetime.date(2025, 11, 24): '(تخمین زده) کشته\u200cشدن فاطمه زهرا', datetime.date(2025, 1, 13): '(تخمین زده) زادروز علی بن ابی\u200cطالب', datetime.date(2025, 1, 27): '(تخمین زده) مبعث', datetime.date(2025, 2, 14): '(تخمین زده) زادروز حجت بن الحسن', datetime.date(2025, 3, 30): '(تخمین زده) عید فطر', datetime.date(2025, 3, 31): '(تخمین زده) عید فطر', datetime.date(2025, 4, 23): '(تخمین زده) کشته\u200cشدن جعفر صادق', datetime.date(2025, 6, 6): '(تخمین زده) عید قربان', datetime.date(2025, 6, 14): '(تخمین زده) عید غدیر'}


<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
تقویم جلالی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
کتابخانه‌های دیگری در پایتون وجود دارند که ویژگی‌های تقویم جلالی را در اختیار ما می‌گذارند. کتابخانه خیام (<code>khayyam</code>) یکی از این کتابخانه‌هاست. در سلول زیر نمونه‌ای از کدهای توسعه‌یافته به کمک این کتابخانه را با هم می‌بینیم:
</font>
</p>

In [10]:
%pip install khayyam
from khayyam import JalaliDate
nowruz = JalaliDate(1402, 1, 1)
nowruz

Defaulting to user installation because normal site-packages is not writeable
Collecting khayyam
  Downloading Khayyam-3.0.17.tar.gz (46 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: khayyam
  Building wheel for khayyam (setup.py): started
  Building wheel for khayyam (setup.py): finished with status 'done'
  Created wheel for khayyam: filename=Khayyam-3.0.17-py3-none-any.whl size=53235 sha256=62f1cd0ecd5dd792071c7f28d918654b950e4863193d90883f84f94f1fccaa01
  Stored in directory: c:\users\josef\appdata\local\pip\cache\wheels\59\aa\66\54af532342776d3a4da48c4f00b7b446d38dcb52bfc20cf84b
Successfully built khayyam
Installing collected packages: khayyam
Successfully installed khayyam-3.0.17
Note: you may need to restart the kernel to use updated packages.

C:\Users\josef\AppData\Roaming\Python\Python313\site-packages\khayyam\algorithms.py:18: UserWarning: The C extension is not available. Switching to fallback python pure algorithms,so it's about 1000X slower than C implementation of the algorithms.
  warnings.warn(

khayyam.JalaliDate(1402, 1, 1, Seshanbeh)