<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
ویژگی‌های دسته‌ای
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
خواندن مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
ابتدا نیاز است فایل مجموعه‌داده‌ی بدون مقادیر گم‌شده (<code>beijing_no_missing.csv</code>) را بخوانیم.
</p>

In [1]:
import pandas as pd
# reading the dataset
df = pd.read_csv('../beijing_no_missing.csv', encoding='gbk', low_memory=False)

In [2]:
df

,url,id,Lng,Lat,Cid,tradeTime,DOM,followers,totalPrice,price,...,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,price_category,buildingStrucure_ismissing,buildingType_ismissing
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030,116.475489,40.019520,1111027376244,2016-08-09,1464.0,106,415.0,31680,...,steel-concrete composite,0.217,has elevator,no,has subway,7,56021.0,average,False,False
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217,116.453917,39.881534,1111027381879,2016-07-28,903.0,126,575.0,43436,...,steel-concrete composite,0.667,has elevator,yes,no subway,7,71539.0,average,False,False
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636,116.561978,39.877145,1111040862969,2016-12-11,1271.0,48,1030.0,52021,...,steel-concrete composite,0.500,has elevator,no,no subway,7,48160.0,average,False,False
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841,116.438010,40.076114,1111043185817,2016-09-30,965.0,138,297.5,22202,...,steel-concrete composite,0.273,has elevator,no,no subway,6,51238.0,cheap,False,False
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653,116.428392,39.886229,1111027381174,2016-08-28,927.0,286,392.0,48396,...,mixed,0.333,no elevator,yes,has subway,1,62588.0,average,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318814,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016-06-10,1.0,8,350.0,20580,...,steel-concrete composite,0.333,no elevator,yes,no subway,3,36545.0,cheap,False,False
318815,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016-06-10,1.0,1,108.8,31006,...,steel-concrete composite,0.222,has elevator,no,has subway,3,54282.0,average,False,False
318816,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016-06-05,1.0,2,359.0,35138,...,steel-concrete composite,0.500,has elevator,yes,no subway,3,46927.0,average,False,False
318817,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016-06-12,10.0,4,720.0,40373,...,mixed,0.500,no elevator,yes,no subway,3,54842.0,average,False,False
318818,https://bj.lianjia.com/chengjiao/BJYZ92363553....,BJYZ92363553,116.497474,39.810115,1111027377957,2016-06-11,1.0,0,450.0,48675,...,steel-concrete composite,1.000,has elevator,no,has subway,3,54282.0,average,False,False

<h2 dir="rtl" align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
تبدیل ویژگی‌های دسته‌ای
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
ابتدا نگاهی به مقادیر ستون <code>renovationCondition</code> بیندازیم:
</font>
</p>

In [3]:
df['renovationCondition'].value_counts()

renovationCondition
other         118740
hardcover     117438
Simplicity     77251
rough           5390
Name: count, dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
ساده‌ترین راه برای تبدیل ستون‌های اسمی به عددی، استفاده از یک دیکشنری برای تبدیل هر دسته به یک عدد است. در این روش، دسته‌ها با استفاده از یک دیکشنری به اعداد <code>0</code> تا <code>n-1</code> نگاشت می‌شوند. (<code>n</code> تعداد دسته‌ها است). با کد زیر می‌توانیم ستون ‍<code>renovationCondition</code> را به عدد تبدیل کنیم:
</font>
</p>

In [4]:
mapping = {'other': 0,
           'hardcover' : 1,
           'Simplicity' : 2,
           'rough' : 3}

df['Mapping'] = df['renovationCondition'].map(mapping)

df['Mapping'].value_counts()

Mapping
0    118740
1    117438
2     77251
3      5390
Name: count, dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
به کمک کلاس <code>LabelEncoder</code> در کتابخانه‌ی <code>scikit-learn</code> نیز می‌توانیم همین کار را به شکل ساده‌تر انجام دهیم:
</font>
</p>

In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['LabelEncoding'] = label_encoder.fit_transform(df['renovationCondition'])

df['LabelEncoding'].value_counts()

LabelEncoding
2    118740
1    117438
0     77251
3      5390
Name: count, dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
بیایید، ستون <code>renovationCondition</code> را بصورت one-hot کدگذاری کنیم. برای این کار می‌توانیم از تابع <code>get_dummies</code> کتابخانه‌ی <code>pandas</code> کمک بگیریم.
</font>
</p>

In [6]:
dummies = pd.get_dummies(df['renovationCondition'])
dummies.head()

   Simplicity  hardcover  other  rough
0        True      False  False  False
1       False       True  False  False
2        True      False  False  False
3       False      False   True  False
4       False      False  False   True

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
اگر بخواهیم حاصل این کدگذاری را به دیتافریم اصلی خود اضافه کنیم می‌توانیم از کد زیر کمک بگیریم:
</font>
</p>

In [7]:
encoded_df = pd.concat([df, dummies], axis=1)

In [8]:
encoded_df.head()

,url,id,Lng,Lat,Cid,tradeTime,DOM,followers,totalPrice,price,...,communityAverage,price_category,buildingStrucure_ismissing,buildingType_ismissing,Mapping,LabelEncoding,Simplicity,hardcover,other,rough
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030,116.475489,40.019520,1111027376244,2016-08-09,1464.0,106,415.0,31680,...,56021.0,average,False,False,2,0,True,False,False,False
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217,116.453917,39.881534,1111027381879,2016-07-28,903.0,126,575.0,43436,...,71539.0,average,False,False,1,1,False,True,False,False
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636,116.561978,39.877145,1111040862969,2016-12-11,1271.0,48,1030.0,52021,...,48160.0,average,False,False,2,0,True,False,False,False
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841,116.438010,40.076114,1111043185817,2016-09-30,965.0,138,297.5,22202,...,51238.0,cheap,False,False,0,2,False,False,True,False
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653,116.428392,39.886229,1111027381174,2016-08-28,927.0,286,392.0,48396,...,62588.0,average,False,False,3,3,False,False,False,True